name: "swiss_financial_health_elt"
version: "1.0.0"
config-version: 2

profile: "swiss_financial_health_elt"

model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]

models:
  swiss_financial_health_elt:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
